version: '2.0'
services:
  influxdb:
    image: influxdb:1.7.0
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
 grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
     - 'configuration.env'
    user: "0"
    links:
     - influxdb
    volumes:
     - /path/to/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini

